stages:
  prepare:
    cmd: python3 src/prepare.py
    deps:
    - data/raw
    - src/prepare.py
    outs:
    - data/prepared/test.csv
    - data/prepared/train.csv
  train:
    cmd: python3 src/train.py
    deps:
    - data/prepared/train.csv
    - src/train.py
    params:
    - train.alpha
    - train.max_iter
    outs:
    - model/model.joblib
  evaluate:
    cmd: python3 src/evaluate.py
    deps:
    - data/prepared/test.csv
    - data/raw
    - model/model.joblib
    - src/evaluate.py
    metrics:
      - metrics/accuracy.json:
          cache: false